"""
get_activities
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from airflow.models import Variable
from astro import sql as aql
import pandas as pd
import pendulum

from airflow.models import Variable
import requests

@aql.dataframe(task_id="fetch_activity")
def fetch_activity_func():
    r = requests.get(Variable.get("API"))
    return r.json()

@aql.dataframe(task_id="print_activity")
def print_activity_func(fetch_activity: pd.DataFrame):
    print(fetch_activity)

default_args={
    "owner": "Merwane Bouri,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-07-24", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Merwane Bouri": "mailto:merwane.bouri@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clyzyam6w00ra01pc85ulgexy/cloud-ide/clyzzk0rq00yn01ltll2qi7k3/clyzzkjp200yt01ltnm5sook6",
    },
)
def get_activities():
    fetch_activity = fetch_activity_func()

    print_activity = print_activity_func(
        fetch_activity,
    )

dag_obj = get_activities()
